apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTIyMDEzMDExMzUzOFoXDTMyMDEyOTExMzUzOFowFTETMBEGA1UE
    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMK2
    nsU0OTbzoI5mLPoSi1jCYYLZ8qVX3VK/bHneSN1WaWEO/B3hRY2JrmyhtfNDFDzZ
    eNZcLj4z0ApA3vEjSXMGbaHwao1HjgZWGC5lzPB0HwyWJmQKg6glsYJ3G+Wpfkdm
    7998qTTp2nJuneDvzzevzblWCewPxJczMgwjl5yimbf/FEFUavT9LvtF6OQKbiIc
    Ywe2qLeds3YJm8tmVwgo+e4Bql1w0BgE52X0mam806IQWrkomSfVMeMM/qbQ1uhp
    KB8DRX3CO3jskzPj5V1uo2DNqHeCSl/AEmGDL1ILgx5IKtwEoSRX58xVXIFdaWen
    fctMsfv8i8iFwtkgy+kCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBQmM2ni8+H84L/W8CpsGyM0iwgtSzANBgkqhkiG9w0BAQsFAAOCAQEAnW0ftYw7
    YQevBC3EBmoBMhsw0wvhY6Xq3kSLZbhhqaE0KTuQ8MQ09Ng0V9j29l/Vj2/M0dIb
    lzbFi9C2Y2Xl9GtBoXWnn2Ty8FBherCLwvBvspeG1bYHd94+gqbyd1JmTakWs3ri
    X1pJQv0OG+DVKpfDJW9Sdj6EX69P5JahDOCJVXnkIk78Hypd7+hhIwECivvN2KeE
    6f6+NoeqPXE5kq7WlaeBAJ3pkiIFb3N8nT4j5KENnlSRCiZtKygGAm4cLszOHl8i
    bORtMXu+TBoGK8ax5tGtx8y+kjqCOFcYt6WBnTClENPQQCCLjv9v3HQNWPyUQOxu
    sapTOi2nbnqZ0w==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/description: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-31T15:01:05Z"
  name: kube-root-ca.crt
  namespace: guestbook
